#' 计算由hc聚类所产生小群落的群落平均功能性状值 / Calculate the community mean functional trait values of the mirror communities generated by HC clustering
#' @description 计算由hc聚类所产生小群落的群落平均功能性状值 / Calculate the community mean functional trait values of the mirror communities generated by HC clustering
#'
#' @param entity 植物个体的分布坐标与物种 / Distribution coordinates and species of plant individuals
#' @param traits 物种的功能性状 / Functional traits of species
#' @param minx 核心区边界，最小x / Core area boundary, minimum x
#' @param miny 核心区边界，最小y / Core area boundary, minimum y
#' @param maxx 核心区边界，最大x / Core area boundary, maximum x
#' @param maxy 核心区边界，最大y / Core area boundary, maximum y
#' @param scale hc聚类的scale参数 / scale parameter of HC clustering
#' @param edge 基于边界筛选小群落的方法，可选"inside"与"centroid" / Method for screening mirror communities based on boundaries, with optional "inside" and "centroid"
#'
#' @return 小群落的平均功能性状值 / Mean functional trait values of mirror communities
#' @export
#'
#' @examples
#' entity=M.COMMUNITIES::entity
#' traits=M.COMMUNITIES::traits
#' CWM_hc_m_communities(entity,traits,minx=5,miny=5,maxx=45,maxy=45,scale=5,edge="inside")
CWM_hc_m_communities=function(entity,traits,minx,miny,maxx,maxy,scale,edge)
{
  library(FD)
  #####################
  #####################
  area=(max(entity[,1])-min(entity[,1]))*(max(entity[,2])-min(entity[,2]))
  n_population=nrow(entity)
  D=n_population/area
  if (missing(scale)) {
    scale= sqrt(D)
  }
  if (missing(minx))
  {
    minx=min(entity[,1])
  }
  if (missing(maxx))
  {
    maxx=max(entity[,1])
  }

  if (missing(miny))
  {
    miny=min(entity[,2])
  }
  if (missing(maxy))
  {
    maxy=max(entity[,2])
  }
  ################################
  abundance_hc_m_communities=function(entity,minx,miny,maxx,maxy,scale,edge)
  {
    library(FD)
    #####################

    #####################
    area=(max(entity[,1])-min(entity[,1]))*(max(entity[,2])-min(entity[,2]))
    n_population=nrow(entity)
    D=n_population/area
    if (missing(scale)) {
      scale= sqrt(D)
    }
    if (missing(minx))
    {
      minx=min(entity[,1])
    }
    if (missing(maxx))
    {
      maxx=max(entity[,1])
    }

    if (missing(miny))
    {
      miny=min(entity[,2])
    }
    if (missing(maxy))
    {
      maxy=max(entity[,2])
    }

    ################################
    hc_m_community_classification=function(entity,minx,miny,maxx,maxy,scale,edge)
    {
      library(stats)
      area=(max(entity[,1])-min(entity[,1]))*(max(entity[,2])-min(entity[,2]))
      n_population=nrow(entity)
      D=n_population/area
      if (missing(scale)) {
        scale= sqrt(D)
        minPts=2
      }
      if (missing(minx))
      {
        minx=min(entity[,1])
      }
      if (missing(maxx))
      {
        maxx=max(entity[,1])
      }

      if (missing(miny))
      {
        miny=min(entity[,2])
      }
      if (missing(maxy))
      {
        maxy=max(entity[,2])
      }
      dist_mat=dist(entity[,1:2])

      hc=hclust(dist_mat,method = "complete")
      m_community_class=cutree(hc, h = scale)
      result=cbind(entity,m_community_class)
      result=result[order(result[,4]),]
      result

      class=c(NA)

      for(i in 1:max(result$m_community_class))
      {
        result_i=result[which(result$m_community_class==i),]
        if(edge=="inside")
        {    if(
          length(which(result_i[,1]>minx & result_i[,1]<maxx & result_i[,2]>miny & result_i[,2]<maxy))==0
        )
        {class=c(class,i)}
        }
        if(edge=="centroid")
        {
          centroid=apply(result_i[,1:2],2,mean)
          if(
            length(which(centroid[1]>minx & centroid[1]<maxx & centroid[2]>miny & centroid[2]<maxy))==0
          )
          {class=c(class,i)}
        }

      }

      class=class[-1]
      result=result[! result$m_community_class %in% class,]
      result$m_community_class=match(result$m_community_class, sort(unique(result$m_community_class)))
      result
    }
    ##################
    class=hc_m_community_classification(entity,minx,miny,maxx,maxy,scale,edge)
    ###################
    spe=levels(as.factor(entity$species))
    abundance=rep(NA,length(spe)+1)
    abundance_i=numeric()
    n_species=length(spe)
    ##################
    n=max(class$m_community_class)
    for (i in 1:n)
    {
      m_community_i=subset(class,class$m_community_class==i)

      for (j in 1:n_species)
      {
        m_community_i_species=subset(m_community_i,m_community_i$species==spe[j])
        abundance_i[j] =nrow(m_community_i_species)
        abundance_i[j+1]=i

      }
      abundance=rbind(abundance,abundance_i)
      colnames(abundance)=c(spe,"m_community_ID")
    }

    abundance=abundance[-1,]
    rownames(abundance)=paste("m_community",1:nrow(abundance))
    abundance
  }
  abundance=abundance_hc_m_communities(entity,minx,miny,maxx,maxy,scale,edge)
  traits=traits[order(rownames(traits)),]
  CWM_m_comunity=rep(NA,ncol(traits)+1)
  CWM_m_comunity_i=numeric()
  for (i in 1:nrow(abundance))
  {
    abun=abundance[i,-ncol(abundance)]
    abun=as.matrix(abun)
    abun=t(abun)
    CWM_m_comunity_i=functcomp(traits, abun)
    CWM_m_comunity_i$m_community_ID=i
    CWM_m_comunity=rbind(CWM_m_comunity,CWM_m_comunity_i)
  }
  CWM_m_comunity=CWM_m_comunity[-1,]
  rownames(CWM_m_comunity)=paste("m_community",1:nrow(abundance))
  CWM_m_comunity
}

